# Generated by Django 4.2.2 on 2023-09-05 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('trade_code', models.CharField(max_length=50)),
                ('high', models.CharField(max_length=300)),
                ('low', models.CharField(max_length=300)),
                ('open', models.CharField(max_length=300)),
                ('close', models.CharField(max_length=300)),
                ('volume', models.CharField(max_length=300)),
            ],
        ),
    ]
